import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ArrowRight } from "lucide-react";
import SheduleADemoButton from "@/components/scheduleDemoButton";
import NavbarOptions from "@/components/navbarMenu";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className=" h-8 w-screen bg-[#0C1C40]">
          <p className=" flex md:text-xs text-white  justify-center  font-sans text-pretty p-1">
            Just launched: Echo, a WhatsApp live chat platform to make
            contextual conversations that convert.
          </p>
        </div>

        {children}
      </body>
    </html>
  );
}
